name: Preview Deployment

on:
  pull_request:
    branches: [ translators ]

jobs:
  build-test-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Remember work dir
      run: |
        pushd -n $(pwd)
    - name: Checkout olympus-frontend
      uses: actions/checkout@v3
      with:
        repository: OlympusDAO/olympus-frontend
        path: frontend
    - name: Prepare translations dir
      run: |
        rm -rf src/locales/translations/*
    - name: Checkout translations
      uses: actions/checkout@v3
      with:
        path: src/locales/translations
    - name: Go to work dir
      run: |
        popd
    - name: Build UI for production
      run: |
        cd /
        yarn install --frozen-lockfile
        yarn build
